_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.8
            "6": 4.50.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batchSize:
    value: 24
bidirectional:
    value: false
bidirectional_stage2:
    value: true
constantOffsetSD:
    value: 0.2
datasetPath:
    value: /data/willett_data/ptDecoder_ctc
device:
    value: cuda:1
dropout:
    value: 0.4
dropout_stage2:
    value: 0.4
gaussianSmoothWidth:
    value: 2
kernelLen:
    value: 32
kernelLen_stage2:
    value: 4
l2_decay:
    value: 1e-05
l2_decay_stage2:
    value: 1e-05
latentspeech_dim_stage2:
    value: 1024
lrEnd:
    value: 0.02
lrStart:
    value: 0.02
maxTimeSeriesLen:
    value: 1200
nBatch:
    value: 30000
nClasses:
    value: 40
nInputFeatures:
    value: 256
nLayers:
    value: 5
nLayers_stage2:
    value: 3
nUnits:
    value: 1024
nUnits_stage2:
    value: 512
outputDir:
    value: /data/willett_data/outputs/speech2neural_03_22
outputdim_stage2:
    value: 256
seed:
    value: 0
seqLen:
    value: 150
strideLen:
    value: 4
strideLen_stage2:
    value: 1
whiteNoiseSD:
    value: 0.8
