_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batchSize:
    value: 256
datasetPath:
    value: /data/willett_data/ptDecoder_ctc
decoder_dim:
    value: 160
decoder_dim_head:
    value: 16
depth:
    value: 10
device:
    value: cuda:0
dim:
    value: 64
dim_head:
    value: 16
dropout:
    value: 0.1
heads:
    value: 4
learning_rate:
    value: 0.001
masking_ratio:
    value: 0.99
mlp_dim_ratio:
    value: 4
num_decoder_heads:
    value: 4
num_decoder_layers:
    value: 2
num_epochs:
    value: 10000
outputDir:
    value: /data/willett_data/outputs/scratch
patch_size:
    value:
        - 100
        - 2
trial_size:
    value:
        - 100
        - 256
weight_decay:
    value: 1e-05
