_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.1
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.1
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batchSize:
    value: 16
datasetPath:
    value: /home3/skaasyap/willett/data
decoder_dim:
    value: 200
decoder_dim_head:
    value: 10
depth:
    value: 10
device:
    value: cuda:0
dim:
    value: 200
dim_head:
    value: 20
dropout:
    value: 0.1
heads:
    value: 10
learning_rate:
    value: 0.001
masking_ratio:
    value: 0.5
mlp_dim_ratio:
    value: 4
num_decoder_heads:
    value: 20
num_decoder_layers:
    value: 2
num_epochs:
    value: 10000
outputDir:
    value: /home3/skaasyap/willett/outputsscratch
patch_size:
    value:
        - 100
        - 2
trial_size:
    value:
        - 100
        - 256
weight_decay:
    value: 1e-05
