_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batchSize:
    value: 64
bidirectional:
    value: true
constantOffsetSD:
    value: 0.2
datasetPath:
    value: /data/willett_data/ptDecoder_ctc
device:
    value: cuda:1
dropout:
    value: 0.4
gaussianSmoothWidth:
    value: 2
kernelLen:
    value: 32
l2_decay:
    value: 1e-05
lrEnd:
    value: 0.02
lrStart:
    value: 0.02
max_mask_channels:
    value: 20
maxTimeSeriesLen:
    value: 1200
nBatch:
    value: 10000
nClasses:
    value: 40
nInputFeatures:
    value: 256
nLayers:
    value: 5
nUnits:
    value: 1024
outputDir:
    value: /data/willett_data/outputs/speechmodel2
seed:
    value: 0
seqLen:
    value: 150
strideLen:
    value: 4
whiteNoiseSD:
    value: 0.8
