_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batchSize:
    value: 275
datasetPath:
    value: /home3/skaasyap/willett/data_log_both
day_specific:
    value: false
decoder_dim:
    value: 64
decoder_dim_head:
    value: 4
depth:
    value: 10
device:
    value: cuda:0
dim:
    value: 64
dim_head:
    value: 8
dropout:
    value: 0.1
extra_notes:
    value: First run with per epoch shuffling
gaussianSmoothWidth:
    value: 2
heads:
    value: 4
learning_rate:
    value: 0.001
masking_ratio:
    value: 0.6
mlp_dim_ratio:
    value: 4
num_decoder_heads:
    value: 8
num_decoder_layers:
    value: 2
num_epochs:
    value: 10000
outputDir:
    value: /home3/skaasyap/willett/outputs/scratch
patch_size:
    value:
        - 32
        - 2
trial_size:
    value:
        - 32
        - 256
weight_decay:
    value: 1e-05
