_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 1
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
channel_masking:
    value: 20
